### PR TITLE
fix missing -encoding functionality

### PR DESCRIPTION
**Pull request by ChiChou**
This issue (#29) was fixed once, but somehow it was removed from the source then.

### CODE REVIEW

**Comment by zakird** [comment]
This seems fine to me. @dadrian, @zzma any concerns?

**Comment by ChiChou** [comment]
@zakird Oh well, I just found that other probes (like -http) have their own banner field name. This patch has not been finished yet...

**Comment by dadrian** [comment]
@ChiChou any update?

**Comment by ChiChou** [comment]
This bug requires so mange changes. Sorry I'm currently busy on my own project, so I'm temporarily closing the PR and reopen it after I'm done.

**Pull request closed without merging**
