### PR TITLE
Extract String() method from MarshalJSON

### PR DESCRIPTION
**Pull request by corny**
This makes it possible to retrieve the name without marshalling the struct to JSON.
I need it because I use zgrab with my own worker.

### CODE REVIEW

**Comment by dadrian** [comment]
Thanks!

**Comment by corny** [comment]
Wow, I have never had such a fast merge :)

**Comment by dadrian** [comment]
So because I used horrible development practices and merged before I tested the code locally it looks like there's a bug here somewhere that results in the names being corrupted, possibly some sort of threading race condition?

```
      "data": {
        "server_hello": {
          "version": {
            "name": "̃",
            "value": 771
          },
          "random": "oN/vsrl4TKvyiJf1Ui1BtWljkEIcHR51zUGxcu31Rtc=",
          "session_id": "MK8JP1jc5AebrFwuvCJwT6q/TGMrxgAtMAgSFMaUStk=",
          "cipher_suite": {
            "hex": "0xC02F",
            "name": "쀯",
            "value": 49199
```

**Comment by corny** [comment]
Is there a trick to get the test suite running? If i change to src/github.com/zmap/zgrab/ztools/ztls and run `go test` I get lots of errors. Are the `*_test.go` files  maintained at all?

```
./handshake_server_test.go:365: cannot use server.ConnectionState().PeerCertificates (type []*"github.com/zmap/zgrab/ztools/x509".Certificate) as type []*"github.com/zmap/ztools/x509".Certificate in send
./ztls_handshake_test.go:44: ec.Issuer undefined (type *encodedCertificates has no field or method Issuer)
./ztls_handshake_test.go:45: ec.AltNames undefined (type *encodedCertificates has no field or method AltNames)
./ztls_handshake_test.go:46: ec.CommonName undefined (type *encodedCertificates has no field or method CommonName)
./ztls_handshake_test.go:47: ec.ValidationError undefined (type *encodedCertificates has no field or method ValidationError)
./ztls_handshake_test.go:64: sc.Issuer undefined (type *Certificates has no field or method Issuer)
./ztls_handshake_test.go:65: sc.CommonName undefined (type *Certificates has no field or method CommonName)
./ztls_handshake_test.go:66: sc.AltNames undefined (type *Certificates has no field or method AltNames)
./ztls_handshake_test.go:98: c.Valid undefined (type *Certificates has no field or method Valid)
./ztls_handshake_test.go:99: c.ValidationError undefined (type *Certificates has no field or method ValidationError)
./ztls_handshake_test.go:99: too many errors
# github.com/zmap/zgrab/ztools/ztls_test
./example_test.go:53: cannot use roots (type *"github.com/zmap/ztools/x509".CertPool) as type *"crypto/x509".CertPool in field value
FAIL	github.com/zmap/zgrab/ztools/ztls [build failed]
```

**Comment by dadrian** [comment]
The `*_test.go` files are hopelessly out of date. ZGrab is still very much hacked together research code. We're slowly working on improving it, but unfortunately tests have largely fallen behind.

**Pull request merged**
