### PR TITLE
Add coveralls.io to display test coverage

### PR DESCRIPTION
**Pull request by corny**
This pull request also updates Go from 1.4 to 1.4.2.
You need to connect your github Account with Coveralls.io.
The result looks like this: https://coveralls.io/github/corny/zgrab

### CODE REVIEW

**Comment by dadrian** [comment]
This looks like it's only giving coverage for the ztools package? There's no way our test coverage is 74%

**Comment by corny** [comment]
Since there are not tests for the zlib package (yet) the result is correct.

**Comment by corny** [comment]
@dadrian Qou still need to sign in with your github account to https://coveralls.io/ and add the repository.

**Comment by zakird** [comment]
We're waiting on a change to go through in order to do this. Once that's
complete, we'll get it added. @dadrian, please don't do this until touching
base.

**Comment by corny** [comment]
ok

**Pull request merged**
