### PR TITLE
Adding Issuer Alternative Name (IAN) parsing

### PR DESCRIPTION
**Pull request by kumarde**
IAN (Issuer Alternative Name) is an extension that follows exactly the format of SAN (subject alternative name), so we can get parsing for free with a bit of refactoring/renaming.

1. Added data members to the Certificate struct that mirror SAN extension. Do we want this information in a struct (GeneralNames, for example), so we are not repeating ourselves? 

2. Adding tests to ensure that IAN parsing is working correctly. These mirror the SAN tests already in extensions_test.go.

3. Do we need to update zgrab_schema.py?

### CODE REVIEW

**Comment by zakird** [comment]
This looks good to me, but needs to be schemaed. I'll take care of this tomorrow. Can you paste the JSON output for the test certificate you added?

**Comment by kumarde** [comment]
Cool. Here's the JSON output, which I got by running ./zcertificate ian.test.cert and pretty printing. 

{
  "version": 3,
  "serial_number": "13905679301969112323",
  "signature_algorithm": {
    "name": "SHA1WithRSA",
    "oid": "1.2.840.113549.1.1.5"
  },
  "issuer": {
    "common_name": [
      "IAN Test"
    ],
    "country": [
      "US"
    ],
    "locality": [
      "Champaign"
    ],
    "organization": [
      "UIUC"
    ],
    "organizational_unit": [
      "CS"
    ],
    "province": [
      "IL"
    ]
  },
  "issuer_dn": "C=US, ST=IL, L=Champaign, O=UIUC, OU=CS, CN=IAN Test, emailAddress=test@iantest.com",
  "validity": {
    "start": "2016-09-07T21:10:12Z",
    "end": "2017-09-07T21:10:12Z",
    "length": 31536000
  },
  "subject": {
    "common_name": [
      "IAN Test"
    ],
    "country": [
      "US"
    ],
    "locality": [
      "Champaign"
    ],
    "organization": [
      "UIUC"
    ],
    "organizational_unit": [
      "CS"
    ],
    "province": [
      "IL"
    ]
  },
  "subject_dn": "C=US, ST=IL, L=Champaign, O=UIUC, OU=CS, CN=IAN Test, emailAddress=test@iantest.com",
  "subject_key_info": {
    "key_algorithm": {
      "name": "RSA",
      "oid": ""
    },
    "rsa_public_key": {
      "exponent": 65537,
      "modulus": "5Sj63YALzwmLnXNWuFmAZlv6sWelKFbP+SWPPEtsjXGHE8R0rAE6lRjjCPw8CRMIIQgGeyxDuB0kLDiR6gG6aHOOb1hdOcxhS7Cw7YsICeZ7V6fN9+opFGwdKJ998TvWsl1Vw2crfTL0P9YmRivevk9kOVfmj\/dFvqRzLL81CmNnDwfsgqo4l1\/WxpOpB5+gua5Fu+q3WyEk8oPcr5jX5z4d8AVhi1ZUYBr8wNrlR\/RWfTJYqL0uch6hg2dLlzodG7v6kKSH\/GVhPd1+eL4Kp4kNaFiJkHstRDz9YZ0y505Z8VF9V3WRsZ7l6JyyRR7dbqJTwiVYM7uESKN2inDMYw==",
      "length": 2048
    },
    "fingerprint_sha256": "688d5164e9da2ebcbcc8dca96513f500687acc7a70aa025c7f268a75ebc23f71"
  },
  "extensions": {
    "key_usage": {
      "digital_signature": true,
      "key_encipherment": true,
      "value": 5
    },
    "issuer_alt_name": {
      "dns_names": [
        "example.1.com",
        "example.2.com"
      ],
      "email_addresses": [
        "test@iantest.com",
        "test2@iantest2.com"
      ],
      "ip_addresses": [
        "1.2.3.4"
      ],
      "other_names": [
        {
          "id": "1.2.3.4",
          "value": "DCBEQlZ6YjIxbElHOTBhR1Z5SUdsa1pXNTBhV1pwWlhJPQ=="
        }
      ],
      "registered_ids": [
        "1.2.3.4"
      ],
      "uniform_resource_identifiers": [
        "http:\/\/www.insecure.com"
      ]
    },
    "certificate_policies": [
      
    ]
  },
  "signature": {
    "signature_algorithm": {
      "name": "SHA1WithRSA",
      "oid": "1.2.840.113549.1.1.5"
    },
    "value": "NKUyMbXEPqjfHmhThDqPF5onrwqVAtumI0FQtfZs7V1Ve4fPU+Hc7jNvyGzv3h2qynKORbX+ZgXX1yUaVL3VJBpKogwr8ogpVbr5q\/D5KrIwI8nUHF9meMPjDj0imtuE4KqSSvHa9YqT16e1iMwcs9vYEmpetIVs8pGIUp9DtpSKV9sn0ZlaLRO4lA1Cx25N8W5Ue3Qoj78Vl\/lZCIBn4Whqpo\/h5joOlETNyghzm8Cw0PAMviC\/k\/rFstizrWa1c8s60Ex5S3A4cdIvF03U5mwYSGMxgfi7TvD6uRlp\/L7t6VSxHChq3C9j965Xec2qK6klS\/4XXVAizN7\/V\/6TEA==",
    "valid": false,
    "self_signed": true
  },
  "fingerprint_md5": "b930cccf8bf02db782dadb8e7171d783",
  "fingerprint_sha1": "51e9e3ddf2d7d46bd269851efbcb574aa4ac47c1",
  "fingerprint_sha256": "2b96e909ccec2ef95d0ef20678a05844c46308d44a78958b4fa9e474a522683b",
  "spki_subject_fingerprint": "d417ddc01fb3d88a50ed9dca6fd7e1484e6043dc64fc743fbb17f57af10cc13b",
  "tbs_fingerprint": "7729889cecc4fd392a4b1bff3222093345e3cc0a7b8f35b1fb3b2a7201818093",
  "validation_level": "DV",
  "names": [
    "test@iantest.com"
  ]
}

**Comment by dadrian** [comment]
It looks like the test files aren't building. Can you make sure tests pass, and ideally, add your test certificate as a test?

**Comment by kumarde** [comment]
Sorry, there was a random tab introduced in some line of code somewhere that got committed. It's been fixed and should pass now. I've already added my test certificate, and included a test in extensions_test.go. Do I need to add it somewhere else?

**Comment by dadrian** [comment]
LGTM.

**Comment by dadrian** [comment]
I added the output of `openssl x509 -text -noout` to the bottom of your test cert, then manually merged. You're still listed as commit author.

Thanks!

**Pull request closed without merging**
