### PR TITLE
Update Chacha20 cipher ids. Fixes #213

### LINKED ISSUE #213: ztls: CHACHA20_POLY1305 ciphersuites ids
According to [rfc7905](https://tools.ietf.org/html/rfc7905) following cipher suites are defined as:
   TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256   = {0xCC, 0xA8}
   TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = {0xCC, 0xA9}
   TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256     = {0xCC, 0xAA}

   TLS_PSK_WITH_CHACHA20_POLY1305_SHA256         = {0xCC, 0xAB}
   TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256   = {0xCC, 0xAC}
   TLS_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256     = {0xCC, 0xAD}
   TLS_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256     = {0xCC, 0xAE}

ztls appears to have different ids for them:
https://github.com/zmap/zgrab/blob/ae5ee0978edafc7ba8d3da48acfaa2c003cb890c/ztools/ztls/cipher_suites.go#L793-L795

### PR DESCRIPTION
**Pull request by SergeyFrolov**

### CODE REVIEW

**Comment by SergeyFrolov** [comment]
You mean append suffix "_OLD" to old ids and add new ones?

**Comment by SergeyFrolov** [comment]
Or just change id? Not sure how this is used

**Comment by zakird** [comment]
Append `_OLD` to old ones and add new ones

**Comment by dadrian** [comment]
Thanks!

**Pull request merged**
