### PR TITLE
Refactor fingerprint creation

### PR DESCRIPTION
**Pull request by corny**

### CODE REVIEW

**Comment by dadrian** [comment]
Is there a reason the slices passed by pointer to the Fingerprint() functions?

**Comment by corny** [comment]
Is `[]byte(in.Raw)` really a slice? I want to avoid call by value and I am not sure if I need pointers in this case.

**Comment by dadrian** [comment]
`in.raw` is already a byte slice, so you should just be able to pass it directly without even calling `raw := []byte(in.Raw)`. 

Also, all of the hash libraries still need to be imported for side-effects so that `crypto.RegisterHash` is called for each hash function used during the verification process, e.g.

```
import _ "crypto/md5"
```

**Comment by corny** [comment]
I updated my pull request. I also:
* renamed String() to Hex()
* added SHA512Fingerprint() for future use

**Comment by dadrian** [comment]
Thanks!

**Pull request merged**
