### PR TITLE
Add BACNet package

### LINKED ISSUE #83: Implement BacNet

### PR DESCRIPTION
**Pull request by dadrian**
Start basic definitions of constants and message types.

Not ready to merge yet. Will fix #83.

### CODE REVIEW

**Comment by dadrian** [comment]
@amirian28 can you double check the schema I pushed in the last commit

**Comment by zakird** [comment]
I would make vendor_name, model_name, description etc into

AnalyzedString(es_include_raw=True)

**Comment by amirian28** [comment]
This seems fine to me.

**Comment by dadrian** [comment]
I think we're good to merge.

**Pull request merged**
