### PR TITLE
TLSCertsOnly Option

### PR DESCRIPTION
**Pull request by jcrowgey**
This PR is connected to new functionality proposed for zcryto: https://github.com/zmap/zcrypto/pull/100

Scanning goes faster if you don't continue the TLS handshake after getting the certs, and furthermore if you don't parse the TLS Certs on the same host that scans them.  With this option you can scan more hosts faster (by moving on before completing the TLS handshake) and you can collect certificates, diff them against a store of parsed certificates, and only parse the new ones.

### CODE REVIEW

**Comment by jcrowgey** [comment]
Note: CI fails because the PR requires the proposed changes to zmap/zcrypto.

**Comment by jcrowgey** [comment]
I've updated this PR to use the listen for the ErrCertsOnly when using the CertsOnly option from the zcrypto/tls package.

**Comment by dadrian** [comment]
@jcrowgey I reran the build now that ZCrypto is updated, but it looks like there's some other incompatibility with `InsecureSkipVerify`. Can you investigate?

**Comment by jcrowgey** [comment]
@dadrian I believe the build is failing because I updated this PR to use the `InsecureSkipValidation` option that I propose in https://github.com/zmap/zcrypto/pull/103.

I see now that it would probably be better to make that a separate PR.

I'll revise this PR to *only* implement `--tls-certs-only` since that functionality is now in ZCrypto.  Then I'll make a separate PR for ZGrab connected to ZCrypto#103 (finish handshake but skip validation).

**Comment by jcrowgey** [comment]
I've rolled back the commits related to zmap/zcrypto#103, I'm going to try closing and reopening this PR to trigger a travis rebuild (https://github.com/travis-ci/travis-ci/issues/576#issuecomment-65317915 ).

**Pull request merged**
